import '@sass/styles/main.scss';
import { Public_Sans } from 'next/font/google';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const publicSans = Public_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={publicSans.className}>
        <main className='auth'>{children}</main>
      </body>
    </html>
  )
}
